# Generated by Django 6.0.6 on 2026-07-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "label",
                    models.CharField(
                        choices=[("spam", "Spam"), ("ham", "Ham")], max_length=4
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence percentage (0-100)"),
                ),
                ("spam_probability", models.FloatField(default=0.0)),
                ("ham_probability", models.FloatField(default=0.0)),
                ("text_length", models.IntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual Input"), ("batch", "Batch Upload")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prediction",
                "verbose_name_plural": "Predictions",
                "ordering": ["-created_at"],
            },
        ),
    ]
